project_id = "xneoovjmwhzzphwlwojc"

[functions.create-live-orders-from-comment]
verify_jwt = false

[functions.fetch-facebook-orders]
verify_jwt = false

[functions.fetch-partner-status]
verify_jwt = false

[functions.fetch-tpos-products]
verify_jwt = false
